#!/usr/bin/env node
/**
 * Copy each plugin's README from GitHub into `src/content/plugins/<id>.md`, which /plugins/<id>/
 * renders below the plugin's facts.
 *
 *   node scripts/sync-plugins.mjs [--ref <git ref>] [--check]
 *
 * **Why `main` by default, not the release tag.** A README is documentation, and documentation is
 * fixed on `main` without cutting a plugin release — a release is a code event, and a lockstep
 * repository bumps every plugin for one. Pinning to the tag would freeze a typo until the next
 * release. What must match the release — the version, `minKit`, the `@<tag>` install command —
 * comes from `src/data/plugins.ts`, never from the README, so the page stays exact about the
 * release while the prose tracks the docs. `--ref <tag>` pins it when that is ever wrong.
 *
 * The site is its own repository and must build without GitHub, so the result is committed data,
 * the same arrangement as `sync:releases`. Rewrites on the way in: the leading `# title` and the
 * `> summary` under it are dropped (the page has its own); a link to another plugin's directory
 * or README becomes that plugin's page here; any other relative link becomes an absolute GitHub
 * URL at the same ref.
 *
 * `--check` fetches and compares, writes nothing, and exits 1 when a committed copy is stale or
 * missing. The plugin list is read from `src/data/plugins.ts` itself (Node ≥ 23.6 strips its
 * types), so there is no second list to keep in step.
 * Exit 0 ok · 1 stale, missing or a fetch failed · 2 usage.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const OUT = path.join(ROOT, 'src', 'content', 'plugins')

const args = process.argv.slice(2)
let ref = 'main'
let check = false
for (let i = 0; i < args.length; i++) {
	if (args[i] === '--ref' && args[i + 1]) ref = args[++i]
	else if (args[i] === '--check') check = true
	else {
		process.stderr.write('usage: node scripts/sync-plugins.mjs [--ref <git ref>] [--check]\n')
		process.exit(2)
	}
}

let PLUGINS
try {
	;({ PLUGINS } = await import(path.join(ROOT, 'src', 'data', 'plugins.ts')))
} catch (err) {
	process.stderr.write(`cannot read src/data/plugins.ts (${err.message}) — this needs Node ≥ 23.6\n`)
	process.exit(1)
}

/** `https://github.com/o/r` → `o/r`. */
const slugOf = (repo) => new URL(repo).pathname.replace(/^\/|\.git$/g, '')

/** `plugins/analytics` → the plugin whose subdir it is, for links between plugins. */
const bySubdir = new Map(PLUGINS.filter((p) => p.subdir).map((p) => [p.subdir, p.id]))

/**
 * Rewrite one markdown link target. `base` is the README's directory, repository-relative.
 * Absolute URLs, anchors and mail links are left alone.
 */
export function rewriteLink(target, { repo, base, ref: at }) {
	if (/^([a-z]+:|#|\/\/)/i.test(target)) return target
	const [file, hash = ''] = target.split('#')
	const resolved = path.posix.normalize(path.posix.join(base, file))
	const plugin = bySubdir.get(resolved.replace(/\/(README\.md)?$/, ''))
	if (plugin) return `/plugins/${plugin}/${hash ? `#${hash}` : ''}`
	const kind = file.endsWith('/') || !/\.[a-z0-9]+$/i.test(file) ? 'tree' : 'blob'
	return `https://github.com/${slugOf(repo)}/${kind}/${at}/${resolved.replace(/\/$/, '')}${hash ? `#${hash}` : ''}`
}

/** The README as the page wants it: no title, no summary, every relative link made absolute. */
export function transform(markdown, ctx) {
	const body = markdown
		.replace(/^﻿?#\s[^\n]*\n+/, '')
		.replace(/^(>[^\n]*\n)+\n*/, '')
	// `[text](target)` and `![alt](target)`, but never inside a fenced code block.
	return body
		.split(/(```[\s\S]*?```)/)
		.map((chunk, i) =>
			i % 2 === 1
				? chunk
				: chunk.replace(/(!?\[[^\]]*\])\(([^)\s]+)\)/g, (_, label, target) => `${label}(${rewriteLink(target, ctx)})`)
		)
		.join('')
		.trimEnd()
}

const withReadme = PLUGINS.filter((p) => p.readme)
let failed = false
for (const p of withReadme) {
	const url = `https://raw.githubusercontent.com/${slugOf(p.repo)}/${ref}/${p.readme}`
	let text
	try {
		const res = await fetch(url)
		if (!res.ok) throw new Error(`HTTP ${res.status}`)
		text = await res.text()
	} catch (err) {
		process.stderr.write(`✖ ${p.id}: ${url} — ${err.message}\n`)
		failed = true
		continue
	}
	const source = `https://github.com/${slugOf(p.repo)}/blob/${ref}/${p.readme}`
	const body = transform(text, { repo: p.repo, base: path.posix.dirname(p.readme), ref })
	const next = `---\n# Generated by \`npm run sync:plugins\` — edit the plugin's README, not this file.\nsource: ${source}\n---\n\n${body}\n`
	const file = path.join(OUT, `${p.id}.md`)
	const current = existsSync(file) ? readFileSync(file, 'utf8') : null
	if (check) {
		if (current !== next) {
			process.stderr.write(`✖ ${p.id}: src/content/plugins/${p.id}.md is ${current ? 'stale' : 'missing'}\n`)
			failed = true
		}
		continue
	}
	mkdirSync(OUT, { recursive: true })
	writeFileSync(file, next)
	process.stdout.write(`${current === next ? '·' : '✔'} ${p.id} ← ${source}\n`)
}

if (check && !failed) process.stdout.write(`plugins ok — ${withReadme.length} README(s) match ${ref}\n`)
if (check && failed) process.stderr.write('run `npm run sync:plugins` and commit the result\n')
process.exit(failed ? 1 : 0)
